### ISSUE TITLE
Updates in Home Assistant 0.87 & 0.88

### ISSUE THREAD

**Issue by r3m0dul8** [pnbruckner/homeassistant-config#100]
Hey buddy, something you may want to work into your wiki as changes to 0.88 have constants moved so therefore locations are broken.

Fix for this in config/custom_components make a new dir called "life360" and move the file "life360.py" from config/custom_components/device_tracker/ to newly created folder config/custom_components/life360/ then rename file from "life360.py" to "device_tracker.py"

Done, not an issue but I believe efficiency is key

Dave.

**Comment by pnbruckner** [comment]
Thanks. Yes, I'm aware of these changes in 0.87 & 0.88. I'll be enhancing the documentation accordingly.
