### ISSUE TITLE
life360 address Attribute not working

### ISSUE THREAD

**Issue by Dmxsir** [pnbruckner/homeassistant-config#119]
I'm not getting the address .

**Comment by pnbruckner** [comment]
Do you mean the address attribute is null? If so, you'll only get a non-null value if 1) you're not in a Life360 Place, and 2) the Life360 server provides an address.

**Comment by Dmxsir** [comment]
yes, the address is null.
I thought it shows the address appears in the life360 app.
Even when I am add a place its just update the zone ,the address still null.

**Comment by pnbruckner** [comment]
Maybe I wasn't clear. If you're in a Life360 Place, then the HA device_tracker entity, by design, will _not_ show an address. So you have to be outside all Life360 Places before an address will show in the HA device_tracker entity. Then you'll only see an address if the Life360 server provides an address. My component does not try to determine an address; it only shows what the Life360 tells it.

**Comment by Dmxsir** [comment]
i didn't add any place in the Life 360, im using zone in HA .

**Comment by Dmxsir** [comment]
the Life360 server provides an address,  Because I see it in the app.

**Comment by pnbruckner** [comment]
Ok. Well, then I don't know why you're not seeing the address in the HA device_tracker entity. About the best I can do is to suggest how you can add some additional debug statements to the code to see exactly what the Life360 server is providing. Let me know if you'd like to try that.

**Comment by Dmxsir** [comment]
yes, sure.
tell what to do.

**Comment by pnbruckner** [comment]
What version of this component are you using?

**Comment by Dmxsir** [comment]
2.8.0

**Comment by pnbruckner** [comment]
Ok, starting on line 437 you should see this code:
```python
            msg = 'Updating {}'.format(dev_id)
            if prev_seen:
                msg += '; Time since last update: {}'.format(
                    last_seen - prev_seen)
            _LOGGER.debug(msg)
```
Add this line just after it:
```python
            _LOGGER.debug('%s', loc)
```
Then restart HA. Make sure you have logger set to debug. Then you should see lines like this in home-assistant.log:
```text
2019-03-21 12:20:12 DEBUG (Thread-14) [custom_components.device_tracker.life360] Updating life360_xxx
2019-03-21 12:20:12 DEBUG (Thread-14) [custom_components.device_tracker.life360] {'isDriving': '0', 'sourceId': 'xxx', 'address2': '', 'source': 'l', 'since': 1553171656, 'latitude': 'xxx', 'placeType': None, 'driveSDKStatus': None, 'wifiState': '1', 'startTimestamp': 1553171656, 'accuracy': '50', 'address1': 'xxx', 'endTimestamp': '1553188666', 'userActivity': None, 'speed': 0, 'shortAddress': '', 'charge': '0', 'timestamp': '1553188666', 'longitude': 'xxx', 'tripId': None, 'inTransit': '0', 'battery': '95', 'name': 'xxx'}
```
The data of interest would be address1, address2, shortAddress, placeType & name. Let me know if any of those include the address information you're seeing on the Life360 app (that you're not seeing in HA.)

**Comment by Dmxsir** [comment]
'address1': None,
 'address2': '',
 'shortAddress': '',
'placeType': None, 
'name': None,

**Comment by pnbruckner** [comment]
Assuming address1 is also an empty string or None, then, unfortunately, it looks like the Life360 server isn't providing the address for some reason, so there's not much I can do about that.

**Comment by Dmxsir** [comment]
okay, well..
Thanks for trying to help.

i will close this issues.
