### ISSUE TITLE
Light Store in History

### ISSUE THREAD

**Issue by jazzyisj** [pnbruckner/homeassistant-config#120]
How does one keep light_store "entities" from appearing in the History?   I have tried every combination I can think of (light.light_store_name, light_store_name, light_store.light_store_name etc.) and cannot get the light_stores out of my history.

Not a critical thing, it's just bugging me.

Great little script BTW - I use it for several things in my setup.  Thanks!

**Comment by pnbruckner** [comment]
```
recorder:
  exclude:
    domains:
      - light_store
```

**Comment by jazzyisj** [comment]
Huh.  Thought I tried that.  Ok, thanks.

**Comment by pnbruckner** [comment]
@jazzyisj, well, strictly speaking, that config keeps state changes for light_store entities from being put in the database, it doesn't prevent history for these entities that already exists in the database from being shown. You might also want:
```text
history:
  exclude:
    domains:
      - light_store
```

**Comment by jazzyisj** [comment]
I have reopened this issue.  I was pretty sure I had tried the suggestion you provided above in the past.

I have deleted my database and exlcuded - light_store from both my recorder and history configurations (and restarted HA), but I still get a light_store entity in my history.  I even verified the history was empty until a light store was created.

With the following configuration my history should be empty, and it is except for the light_store entity.      Maybe I'm totally misunderstanding something here.  Any thoughts?

HA 0.90.1

```
exclude:
  domains:
    - alarm_control_panel
    - alert
    - automation
    - binary_sensor
    - calendar
    - camera
    - counter
    - climate
    - cover
    - delay
    - device_tracker
    - fan
    - group
    - history_graph
    - input_boolean
    - input_datetime
    - input_number
    - input_select
    - input_text
    - light
    - light_store
    - media_player
    - notify
    - persistent_notification
    - person
    - proximity
    - scene
    - script
    - sensor
    - switch
    - sun
    - timer
    - updater
    - weather
    - weblink
    - zwave
```

**Comment by pnbruckner** [comment]
Are you using a different `store_name` by any chance? Because the `store_name` parameter specifies the domain of the temporary entities created. The default is `light_store`, but by using the `store_name` option you can change it to something else. You need to list any and all `store_name`'s you use.

**Comment by pnbruckner** [comment]
@jazzyisj any update?

**Comment by jazzyisj** [comment]
Sorry, life gets in the way sometimes... lol

YES!  I think I finally figured this out (with your help!).  Your last message there kinda clued me in, then I happened to catch a light store name in the unused entities page that finished turning the light bulb on.

I do use a custom light store name in every instance.  So adding light_store to excluded domains does nothing.    The light store **name** must be added to the excluded domains.

```
history:
  exclude:
    domains:
      - alarm_pending_light_store
      - house_alert_light_store
      - smoke_alarm_light_store
      - garage_door_light_store
```

It wasn't a big deal, didn't impact usage but this has been driving me crazy!  Thank you for your help!

**Comment by pnbruckner** [comment]
Glad I could help. BTW, I'd exclude those domains from both history _and_ recorder. By excluding it from history, that's just keeping the data from showing on the history page, but the data is still going into the database. If you don't care about the data at all, then excluding it from recorder will reduce the size and update frequency of the database as well.
