### ISSUE TITLE
Illuminance Broken in .91.0

### ISSUE THREAD

**Issue by mrneilix** [pnbruckner/homeassistant-config#127]
Hey, I keep getting this issue. I tried setting it back up, and doing the fix from .89, but neither are working

> Error loading custom_components.illuminance.sensor. Make sure all dependencies are installed
> Traceback (most recent call last):
>   File "/config/custom_components/illuminance/sensor.py", line 20, in <module>
>     from homeassistant.components.sensor.darksky import (
> ModuleNotFoundError: No module named 'homeassistant.components.sensor.darksky'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 183, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/illuminance/sensor.py", line 23, in <module>
>     from homeassistant.components.sensor.darksky import (
> ModuleNotFoundError: No module named 'homeassistant.components.sensor.darksky'

**Comment by pnbruckner** [comment]
Well, they finished the Great Migration, so the modules I was importing from have moved. I'll have to update accordingly. In the meantime, if you just want to get it working, adjust the import statements. E.g., change:
```python
    from homeassistant.components.sensor.darksky import (
        ATTRIBUTION as DSS_ATTRIBUTION)
```
to:
```python
    from homeassistant.components.darksky.sensor import (
        ATTRIBUTION as DSS_ATTRIBUTION)
```

**Comment by mrneilix** [comment]
figured it out, I had to do it for the whole thing:

```
from homeassistant.components.sensor import (
    DOMAIN as SENSOR_DOMAIN, PLATFORM_SCHEMA, SCAN_INTERVAL)
try:
    from homeassistant.components.darksky.sensor import (
        ATTRIBUTION as DSS_ATTRIBUTION)
except ImportError:
    from homeassistant.components.darksky.sensor import (
        ATTRIBUTION as DSS_ATTRIBUTION)
try:
    from homeassistant.components.yr.sensor import (
        ATTRIBUTION as YRS_ATTRIBUTION)
except ImportError:
    from homeassistant.components.yr.sensor import (
        CONF_ATTRIBUTION as YRS_ATTRIBUTION)
from homeassistant.components.darksky.weather import (
    ATTRIBUTION as DSW_ATTRIBUTION, MAP_CONDITION as DSW_MAP_CONDITION)
from homeassistant.const import (
    ATTR_ATTRIBUTION, CONF_ENTITY_ID, CONF_API_KEY, CONF_NAME,
    CONF_SCAN_INTERVAL, EVENT_HOMEASSISTANT_START)
from homeassistant.core import callback
from homeassistant.helpers.aiohttp_client import async_get_clientsession
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.entity import Entity
from homeassistant.helpers.event import (
    async_track_state_change, async_track_time_change)
from homeassistant.helpers.sun import get_astral_event_date
import homeassistant.util.dt as dt_util
```

**Comment by pnbruckner** [comment]
Yep. I'm reopening so I remember to fix the source and release a new version.

**Comment by pnbruckner** [comment]
@mrneilix please see PR #129 for an update that should fix this issue. If you give it a try, please let me know how it works. I haven't tested it at all.

**Comment by danodemano** [comment]
@pnbruckner - stupid question, but how do I try that PR?  I manually edited the file the other day to fix it.  But how can I use the version you have in the PR to confirm it's working?

**Comment by pnbruckner** [comment]
@danodemano you can use:
```text
wget https://github.com/pnbruckner/homeassistant-config/raw/0.91/custom_components/illuminance/sensor.py
```

**Comment by danodemano** [comment]
@pnbruckner - got it.

That's working just fine for me!

![image](https://user-images.githubusercontent.com/1128744/55678233-fc85b980-58c3-11e9-911b-451d9d42e0e8.png)

I trashed the files before downloading too.  So I think that's good!
