### ISSUE TITLE
2x Warnings now - is that normal?

### ISSUE THREAD

**Issue by MightyMilster** [pnbruckner/homeassistant-config#141]
Hi. I am not sure when this started but I seem to have two warnings being logged now after a restart. Have I doubled-up in my setup somehow? Thanks!

This is my setup...
```
/config/custom_components/life360/__init__.py
/config/custom_components/life360/device_tracker.py
/config/custom_components/life360/manifest.json
```
You are using a custom component for **life360.device_tracker** which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

You are using a custom component for **life360** which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.

**Comment by pnbruckner** [comment]
As far as I know that is normal, and is a side effect of providing an `__init__.py` file.

**Comment by MightyMilster** [comment]
Thanks Phil! You rock!
