### ISSUE TITLE
Life360 addon no longer works with homeassistant 0.92

### ISSUE THREAD

**Issue by chiefcomm** [pnbruckner/homeassistant-config#143]
Seems related to several other threads regarding "Unable to find services.yaml for the xxxxxxx integration" related to the new architecture in 0.92. Not knowing much about Python I couldn't make a lot of sense of the issue however there is a fair amount of chatter on this @ https://github.com/home-assistant/home-assistant/issues/23188

**Comment by garywilson4** [comment]
I just added a blank services.yaml file to the Life360 folder

**Comment by chiefcomm** [comment]
I added blank services.yaml file to the Life360 folder in my many attempts to resolve prior to rolling back to 0.91.4 - error persists in 0.92.0 unfortunately.

**Comment by CBPetrovic** [comment]
There is an update for the extension. Mine failed as well but research
revealed a new release. Works like a champ again!

**Comment by CBPetrovic** [comment]
I suggest that anyone using custom components add the custom components
update service as outline in pbruckner's github addon entry.
---------------------------------------------------------------------------
"I ask for so little, and I get so much less in return."

*C. B. Petrovic*
*Merrimack, NH*

**Comment by pnbruckner** [comment]
Hi all. Are you using life360 version 2.9.4 or later? I've tested this myself on 0.92.0 and it seems to work fine without any warnings or errors. If you are using 2.9.4 or later, on HA 0.92.0, and are getting any warnings or errors, could you please post them here?

**Comment by pnbruckner** [comment]
I just tried an experiment. I did a clean install of HA 0.91.4 and custom_updater 4.2.19. I used custom_updater to install life360 2.9.5. Then I restarted HA and although there were the usual warnings about using custom components:
```text
2019-04-26 08:31:27 WARNING (MainThread) [homeassistant.loader] You are using a custom component for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-26 08:31:28 WARNING (MainThread) [homeassistant.loader] You are using a custom component for life360 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-26 08:31:28 WARNING (MainThread) [homeassistant.loader] You are using a custom component for life360.device_tracker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
everything worked fine.

Then I stopped HA and upgraded to 0.92.0. When I restarted, there was the usual custom integration warnings, and a new warning about custom_updater not having a services.yaml:
```text
2019-04-26 08:33:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for custom_updater which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-26 08:33:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for life360 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-04-26 08:33:57 WARNING (MainThread) [homeassistant.helpers.service] Unable to find services.yaml for the custom_updater integration
```
but otherwise everything seemed to work fine.

And although I did this experiment using custom_updater to install life360, I see no reason to believe things would work differently if I had not used custom_updater but rather manually installed life360.

So unless someone using life360 2.9.4 or later with HA 0.92.0 or later can provide some details of real problems, I still don't see an issue.

**Comment by Snake1980** [comment]
Just for info...

I have homeassistant 0.92 on raspbian.
Following life360 installation procedure, I copied the init, device_tracker and manifest under life360 directory. HA starts, I see warning message about custom component (showd for all custom components), but webgui is unreachable (Chrome returns ERR_FAILED).

If I remove `manifest.json` it works.
This is my directory...

```
pi@raspberry:/home/homeassistant/.homeassistant/custom_components/life360 $ ll
total 40
drwxr-xr-x 5 homeassistant homeassistant  4096 Apr 26 16:19 ..
-rw-r--r-- 1 homeassistant homeassistant    53 Apr 26 16:20 __init__.py
-rw-r--r-- 1 homeassistant homeassistant 22196 Apr 26 16:21 device_tracker.py
drwxr-xr-x 3 homeassistant homeassistant  4096 Apr 26 16:21 .

```

**Comment by pnbruckner** [comment]
I haven't verified it, but I believe 0.92.0 will accept (what is now called) a custom integration without a manifest.json file. It "falls back" to looking for REQUIREMENTS and DEPENDENCIES in the Python modules. I can try testing this scenario. The one problem _might_ be where those statements are (i.e., `__init__.py` vs `device_tracker.py`.)

But, I can't explain why HA hung for you when the manifest.json file was present. It certainly does _not_ do that for me.

**Comment by pnbruckner** [comment]
So tested again with all three files installed (i.e., including manifest.json) and it works. Even if I manually uninstall the life360 package first.

Then I removed the life360 package (again), and manifest.json, and it fails:
```text
2019-04-26 10:49:25 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform life360
Traceback (most recent call last):
  File "/home/phil/.homeassistant/custom_components/life360/device_tracker.py", line 171, in setup_scanner
    from life360 import life360, LoginError
ModuleNotFoundError: No module named 'life360'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/phil/test/ha-0.92.0/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 177, in async_setup_platform
    disc_info)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/phil/.homeassistant/custom_components/life360/device_tracker.py", line 176, in setup_scanner
    except LoginError as exc:
UnboundLocalError: local variable 'LoginError' referenced before assignment
```
This is because the REQUIREMENTS & DEPENDENCIES statements are not being found. If I manually install the life360 package (or, e.g., you already had it installed), then it works.

So @Snake1980, I seem to be experiencing the _exact opposite_ of what you're seeing.

This is all very strange. But I've already submitted life360 to become part of the standard HA install, so hopefully before too long it won't matter whether this custom version works or not.

**Comment by Snake1980** [comment]
Before today I had an old life360 version with just two files...

device_tracker.py
composite.py

Maybe I need to try removing custom component files and packages (how?) ???

**Comment by pnbruckner** [comment]
Those are actually two different custom components. And being named that way means they're pretty old.

I would suggest you remove all but the following:
```text
custom_components/composite
custom_components/composite/__init__.py
custom_components/composite/device_tracker.py
custom_components/composite/manifest.json
custom_components/life360
custom_components/life360/__init__.py
custom_components/life360/device_tracker.py
custom_components/life360/manifest.json
```
And these should all be the latest & greatest versions.

You should probably also remove any folder named `__pycache__` directly or indirectly under custom_components.

**Comment by pnbruckner** [comment]
@chiefcomm @garywilson4 @Snake1980 

Can you please update me on how this is going for you? If there's a real problem I want to fix it. But so far all the testing I've done can't reproduce these problems. And it's not clear from what I've read so far if the problems are simply due to using too old of a version of life360 (i.e., before 2.9.4), or an installation problem, or something like that.

**Comment by Snake1980** [comment]
Deleted all files.
Downloaded again

life360/__init__.py
life360/device_tracker.py
life360/manifest.json

HA seems starts, but when I try to open webgui this is the result

![image](https://user-images.githubusercontent.com/7205371/56842069-367a2800-6892-11e9-9ea0-2ffb53030844.png)

(hidden in red my domain and port)

If I delete manifest.json and restart HA, it works fine

**Comment by garywilson4** [comment]
Got mine working by adding the manifest.json

**Comment by pnbruckner** [comment]
@Snake1980 I have no idea what you're showing on the bottom of that picture. Are you sure it's the manifest.json file inside `<config_dir>/custom_components/life360` this is causing your problem?

**Comment by pnbruckner** [comment]
@garywilson4, you had to add a blank `services.yaml` file in `<config_dir>/custom_components/life360`? What happens if you don't do that? What error do you see? Does it just flat out not work without it?

**Comment by Snake1980** [comment]
> @Snake1980 I have no idea what you're showing on the bottom of that picture. Are you sure it's the manifest.json file inside `<config_dir>/custom_components/life360` that is causing your problem?

![image](https://user-images.githubusercontent.com/7205371/56842696-80660c80-6898-11e9-9eb9-3adb9b1f9924.png)

**Comment by pnbruckner** [comment]
@Snake1980 well I have no idea how that can cause the problem you're seeing. Obviously there's something going wrong, but I have no idea how to diagnose the root cause, because I can't see how a file named manifest.json in that directory could cause the web interface to break.

FWIW, I did verify again that if you just have `device_tracker.py` it won't work. If you add `__init__.py` it can work, but only if the life360 package is already installed, or you manually install it before launching HA. Although I haven't tried it, another possibility might be to move the DEPENDENCIES and REQUIREMENTS statements from `device_tracker.py` to `__init__.py`. If you don't have the life360 package installed already, and you don't know how to install it using pip, then this might be an option worth trying.

Sorry, but I have no idea what this happens to you but nobody else I know of.

**Comment by chiefcomm** [comment]
@pnbruckner I'm perplexed the Life360 integration is working perfectly for me today so all good thanks
  __init__.py
  device_tracker.py
  manifest.json
all installed in \custom_components\life360

**Comment by garywilson4** [comment]
> @garywilson4, you had to add a blank `services.yaml` file in `<config_dir>/custom_components/life360`? What happens if you don't do that? What error do you see? Does it just flat out not work without it?

Don’t know tbh but it got rid of the error/warning in the ha logs

**Comment by Snake1980** [comment]
> @Snake1980 well I have no idea how that can cause the problem you're seeing. Obviously there's something going wrong, but I have no idea how to diagnose the root cause, because I can't see how a file named manifest.json in that directory could cause the web interface to break.
> 
> FWIW, I did verify again that if you just have `device_tracker.py` it won't work. If you add `__init__.py` it can work, but only if the life360 package is already installed, or you manually install it before launching HA. Although I haven't tried it, another possibility might be to move the DEPENDENCIES and REQUIREMENTS statements from `device_tracker.py` to `__init__.py`. If you don't have the life360 package installed already, and you don't know how to install it using pip, then this might be an option worth trying.
> 
> Sorry, but I have no idea why this happens to you but nobody else I know of.

I already have life360 package installed in my venv...

```
(homeassistant) homeassistant@snakeberry:/etc $ pip3 list | grep life360
life360                       3.0.0     
```

**Comment by hoffdad** [comment]
Not sure if it's related or if it was only coincidence related to the timing of the release , but after updating to the newest life360 version my sensors were still showing unavailable.  I found that somehow the known_devices.yaml file had MULTIPLE versions of the life360 trackers, all but my original ones were showing as `track: false`.  I deleted all but the original and I was back in business.  If this is unrelated, let me know and I'll delete my post.

**Comment by pnbruckner** [comment]
@hoffdad I'll need a bit more to go on. E.g., what version of HA are you using? What were the differences between the known_devices.yaml entries for a given device? What does your device_tracker configuration look like?

**Comment by hoffdad** [comment]
I'm running Home Assistant 0.93.1. In my trackers.yaml file I have:
```
- platform: life360
  username: !secret life360_username
  password: !secret life360_password
  add_zones: all
  driving_speed: 18
  filename: life360.conf
  home_place: Home
  interval_seconds: 10
  max_gps_accuracy: 200
  prefix: life360
  show_as_state: driving, moving, places
```

Example of my original trackers:
```
life360_firstname_lastname:
  hide_if_away: false
  icon:
  mac:
  name: life360_firstname
  picture: https://xxxxxxxxx.duckdns.org/local/icons/firstname.png
  track: true
```

I deleted them without saving a copy, but the additional trackers that were added somehow looked similar to this:
```
life360_firstname_lastname:
  hide_if_away: false
  icon:
  mac:
  picture: https://original_life360_image_url.com
  track: false
```

**Comment by pnbruckner** [comment]
@hoffdad I guess I was wondering what other configurations you have under `device_tracker`. There are some "global" settings that can affect the default track state which maybe you have with another device_tracker configuration.

Also, the known_devices.yaml file is managed strictly by the component-level device_tracker code (i.e., life360 does not read or write that file.) If there are unusual entries getting added (like multiple entries for the same device_id) then that might be a bug in the device_tracker component code. It has been going through some changes lately, and more I believe are coming.

**Comment by chiefcomm** [comment]
@pnbruckner thought I'd say thanks for the work preparing for 0.94 release happy to say no issues at all since loading 0.94.0 with you new code updates - congrats :-) 

Any plans to have Life360 as an official Home Assistant integration?  Hopefully yes.

**Comment by pnbruckner** [comment]
@chiefcomm Thank you, and glad it's working for you. To answer your question, see https://github.com/home-assistant/home-assistant/pull/24227.
