### ISSUE TITLE
Life360: Is it possible to add to HACS (Home Assistant Community Store)

### ISSUE THREAD

**Issue by vitinhosessa** [pnbruckner/homeassistant-config#146]
I would love if Life360 can be added to HACS (Home Assistant Community Store).

**Comment by pnbruckner** [comment]
Thanks, but as I've said in several other contexts, this is not likely to happen. First I'm trying (somewhat unsuccessfully) to make this a standard component. Second, HACS requires each custom component to be in a separate github repository, which is not the case here, nor do I want to reorganize everything just to suit this HACS requirement.
