### ISSUE TITLE
Life360 not working in 0.94.0b0

### ISSUE THREAD

**Issue by KevinSwitzer** [pnbruckner/homeassistant-config#147]
I noticed the Life360 sensors I have set up stopped working when I updated to 0.94.0b0. I tried updated the Life360 files, and now I get the following error when trying to validate the config:

Configuration invalid
Platform not found: device_tracker.life360

Here's my setup...
/custom_components/life360/\_\_init\_\_.py
/custom_components/life360/device_tracker.py
/custom_components/life360/manifest.json

All were created from Raw. (I also tried using custom_updater, but got the same results.) 
\_\_init\_\_.py says: \_\_version\_\_ = '2.10.0'

No validation errors until I add the following (same as I had previously) to configuration.yaml:

device_tracker:
  \- platform: life360
    username: !secret life360_username
    password: !secret life360_password
    max_gps_accuracy: 200
    prefix: life360
    add_zones: all
    home_place: Home
    show_as_state: driving, moving, places

Even trying to do a server restart from within HA doesn't work unless I comment out the device_tracker stuff in configuration.yaml. 

Any ideas on what can be causing this? Thank you.

**Comment by pnbruckner** [comment]
@KevinSwitzer I have no idea, but it would seem that something changed in 0.94. I'll try to take a look tomorrow...

**Comment by KevinSwitzer** [comment]
@pnbruckner For what it's worth, I tried reverting back to HA 0.93.2 and had the same results.

**Comment by pnbruckner** [comment]
@KevinSwitzer I just tried 0.92.2, 0.93.0, 0.93.1 & 0.93.2, and they all worked fine. However, with 0.94.0b0 & 0.94.0b1, although it loads and warns about the custom life360 custom component/integration:
```text
2019-05-31 09:20:26 INFO (SyncWorker_8) [homeassistant.loader] Loaded life360 from custom_components.life360
2019-05-31 09:20:26 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for life360 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```
it doesn't seem to be running.

I'll do some more debugging to try and figure out why. Thanks for letting me know!

**Comment by KevinSwitzer** [comment]
Thanks so much!!

**Comment by KevinSwitzer** [comment]
Just some more info - I just updated to 0.94.0b1 and still get the following when trying to validate my configuration under Configuration > General:

Configuration invalid
Platform not found: device_tracker.life360

I also see the errors you're seeing in the log.

**Comment by pnbruckner** [comment]
@KevinSwitzer I found the problem. The device_tracker and zone components have had some changes recently, so things I was using were no longer in the same place. I've updated the custom life360 integration and now it seems to work with both 0.93 & 0.94. I'll be checking those changes in shortly.

**Comment by KevinSwitzer** [comment]
@pnbruckner Amazing! Thank you so much for working on this so quickly!

**Comment by pnbruckner** [comment]
@KevinSwitzer ok, 2.10.1 released. Give it a try and let me know if it works for you.

**Comment by KevinSwitzer** [comment]
@pnbruckner Works great now! Thank you again!

**Comment by CBPetrovic** [comment]
FWIW, I went to official Hassio 94.0 and then 94.1 and Life360 did not
start.  I also attempted to install/configure a trend sensor which went
fine, but that also didn't work for Life360.

Downgraded to 0.93.2 and all is running fine.

And for something different, installed HACS and went looking for
custom_components/life360, came up empty.
Is there a future plan to make life360 add-on available via HACS?

---------------------------------------------------------------------------
"I ask for so little, and I get so much less in return."

*C. B. Petrovic*
*Merrimack, NH*

**Comment by pnbruckner** [comment]
@CBPetrovic 

> FWIW, I went to official Hassio 94.0 and then 94.1 and Life360 did not start.

Did you make sure to upgrade to the latest life360 custom component (2.10.1)?

> I also attempted to install/configure a trend sensor which went fine, but that also didn't work for Life360.

I have no idea what a trend sensor has to do with life360.

> And for something different, installed HACS and went looking for
custom_components/life360, came up empty.
Is there a future plan to make life360 add-on available via HACS?

No, there is no plan to reorganize my life360 custom component so that it is compatible with HACS. However, it has been accepted as a standard component and should be available, if all goes normally, in the 0.95 release.

**Comment by CBPetrovic** [comment]
Yes, the component has been upgraded to 2.10.1

Trend sensor - your suggestion to install the trend sensor to get numpy to
install; another user's workaround to get life360 working on 0.94.0b

Good to know about the status of the component becoming standard.

FWIW, I am running hassio, still does not explain working @ 0.93.2 and not
at 0.94.X
---------------------------------------------------------------------------
"I ask for so little, and I get so much less in return."

*C. B. Petrovic*
*Merrimack, NH*

**Comment by pnbruckner** [comment]
@CBPetrovic numpy is only used if you have `time_as` set to `device_or_local` or `device_or_utc`. And there's really nothing special about numpy, other than if you're running on a Pi, in which case I provide instructions on how to install the other pieces numpy requires. I suspect numpy has nothing to do with your issue.

Are there any errors or warnings in home-assistant.log that can help shed some light on why life360 isn't working for you?

Can you set `logger` to `debug` (at least for `life360` and `custom_components.life360`) and see if there are any useful debug messages in home-assistant.log for life360?

**Comment by CBPetrovic** [comment]
working on debugging now, seeing why my entire device_tracker setup is
defunct

---------------------------------------------------------------------------
"I ask for so little, and I get so much less in return."

*C. B. Petrovic*
*Merrimack, NH*

**Comment by pnbruckner** [comment]
@CBPetrovic are you using any other device_tracker platforms (Owntracks, GPSlogger, etc.)? Some people seem to be having problems when using multiple types of device trackers in 0.94.x, especially when some of them have been updated to the newer type (i.e., entity vs "legacy".) FWIW, I just today tried life360 and Owntracks on 0.94.0 & 0.94.1 and they seemed to work fine together for me.

**Comment by CBPetrovic** [comment]
Well, as it turns out. owntracks and life360 don't like living in the same
house.  at least my HA house.and GPS logger has issues as well.

So, for the time being, those two will be banned from darkening my HA
doorstep, given that I can get all the presence detection needs I desire
from Life360

Interestingly, these all seemed to get along prior to 0.94.x

---------------------------------------------------------------------------
"I ask for so little, and I get so much less in return."

*C. B. Petrovic*
*Merrimack, NH*

**Comment by pnbruckner** [comment]
@CBPetrovic owntracks and gpslogger did get transformed from "legacy" trackers to the new entity-based tracker. You're apparently supposed to do a one time "clean up" by removing any entries in known_devices.yaml for owntracks and gpslogger and then restart HA. Did you do that? I wonder if that has something to do with why people are having problems all of a sudden.

But, like I said, I tested Owntracks and life360 with 0.94.x and, at least starting from a clean install, they seem to work together ok.
