### ISSUE TITLE
Life360 Startup problems in HA 0.94.0b3 and 0.94.0b4 

### ISSUE THREAD

**Issue by ccorderod** [pnbruckner/homeassistant-config#149]
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | Europe/Madrid
version | 0.94.0b4
virtualenv | false

````yaml
- platform: life360
  username: !secret life360_un
  password: !secret life360_pw
  prefix: life360
  show_as_state: driving, moving, places
  home_place: Casa
  driving_speed: 18
  max_gps_accuracy: 100
  time_as: device_or_local
  max_update_wait:
    minutes: 45
  interval_seconds: 12
  consider_home: 180
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false



2019-06-02 19:37:56 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
    tracker.see, discovery_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/life360/device_tracker.py", line 311, in setup_scanner
    Life360Scanner(hass, config, see, interval, home_place_name, api)
  File "/config/custom_components/life360/device_tracker.py", line 342, in __init__
    from timezonefinderL import TimezoneFinder
  File "/config/deps/lib/python3.7/site-packages/timezonefinderL/__init__.py", line 3, in <module>
    from .timezonefinderL import TimezoneFinder
  File "/config/deps/lib/python3.7/site-packages/timezonefinderL/timezonefinderL.py", line 9, in <module>
    from numpy import array, empty, float64, fromfile
ModuleNotFoundError: No module named 'numpy'

**Comment by pnbruckner** [comment]
@ccorderod That shouldn't happen. Life360 specifies timezonefinderL 2.0.1 as a requirement, which should cause HA to install it. And timezonefinderL specifies any version of numpy as a requirement, so HA should install that, too. This has been the case in all the testing I've ever done. Have you tried checking to see if HA had some sort of issue installing numpy? Or maybe just try restarting HA and see if you get the same error.

**Comment by ccorderod** [comment]
@pnbruckner I have restarted HA several times :(. Same problem. It seems the HA team is struggling with this release as several platforms/components are broken. Let's wait for a new build to see what happen. Txs.

**Comment by ccorderod** [comment]
@pnbruckner . HA upgraded to 0.94.0b5. Same issue (no module named 'numpy'. I tried to pip3 install numpy from container console. Install crashed :(. Feel free to close the thread as I think the issue as nothing to do with life360. Will keep it updated as we move forward with the builds anyway. Thank you.

**Comment by pnbruckner** [comment]
@ccorderod as a test, you could try temporarily defining a [trend binary_sensor](https://www.home-assistant.io/components/trend/). It also uses numpy, but defines it directly as a requirement. If that works then there must be something wrong with the way indirect requirements (i.e., requirements of packages) are being handled.

**Comment by ccorderod** [comment]
@pnbruckner. trend binary sensor created and working; life360 working now as well.

**Comment by ccorderod** [comment]
@pnbruckner fyi. posted on beta channel on discord:
balloobhoy a las 19:38
The reason we're seeing a bunch of package related issues in this beta is because of the new approach that we're taking to installation. Instead of having a single image with everything in it, we are now installing just the required packages. So if custom integrations didn't properly specify their packages before, it might have worked because the package was installed for another unused integration.

**Comment by pnbruckner** [comment]
I can say for certain that numpy was indirectly installed before. I.e., my custom component specifies timezonefinderL==2.0.1, and timezonefinderL specifies numpy, so as part of installing the requirements for my custom component, it installed both the direct requirement (timezonefinderL) and the _indirect_ requirement (numpy, which is required by numpy.) I know this worked, even when neither were originally installed. So if it doesn't work now, then it seems HA is no longer looking at indirect requirements (i.e., requirements of packages required by HA components.)

**Comment by ccorderod** [comment]
do you want me to post a note on the discord beta channel?

**Comment by pnbruckner** [comment]
I tried to find the conversation on discord. I found the post you referenced by balloob, but I couldn't find the rest of the conversation. What is you username on discord? (I find it difficult when people have different usernames on github, discord & the HA forum. Mine is the same across all of them.)

**Comment by ccorderod** [comment]
@pnbruckner ccordero#1965

**Comment by pnbruckner** [comment]
FWIW, I just did a test with 0.94.3. Seems to work fine:
```text
(homeassistant) $ pip list | grep -e numpy -e timezonefinderL -e life360
life360                 3.0.0
numpy                   1.16.4
timezonefinderL         2.0.1
(homeassistant) $ pip uninstall numpy timezonefinderL life360
...
(homeassistant) $ pip list | grep -e numpy -e timezonefinderL -e life360
(homeassistant) $ hass
...
(homeassistant) $ grep Attempting ~/.homeassistant/home-assistant.log
2019-06-14 08:56:27 INFO (SyncWorker_34) [homeassistant.util.package] Attempting install of life360==3.0.0
2019-06-14 08:56:28 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of timezonefinderL==2.0.1
(homeassistant) $ pip list | grep -e numpy -e timezonefinderL -e life360
life360                 3.0.0
numpy                   1.16.4
timezonefinderL         2.0.1
```
Not sure why this didn't work for you. Maybe there was a bug in the beta release. Anyway, since it seems to work, and since life360 will become a standard component in 0.95, I'll close this.

**Comment by ccorderod** [comment]
@pnbruckner My apologies, I should have close this one. 0.94.b6 fixed the issue. Thank you for your support.
