### ISSUE TITLE
Feature Request - Adopt Hacs (Home Assistant Community Store) tracker.

### ISSUE THREAD

**Issue by juan11perez** [pnbruckner/homeassistant-config#151]
Thank you for your great components. Please consider structuring to work with hacs downloader/updater. 

https://github.com/custom-components/hacs

**Comment by pnbruckner** [comment]
As I've stated several times, I won't be doing this for my custom amcrest & life360 components since the majority of the functionality has been, and will be, part of standard integrations either already available or available soon. I'll consider doing it for composite, illuminance & sun.

**Comment by ikifar2012** [comment]
But this means that automatic updating will be broken @pnbruckner because the custom updater is being deprecated:
https://github.com/custom-components/custom_updater

**Comment by juan11perez** [comment]
Thank you

**Comment by pnbruckner** [comment]
@ikifar2012 which components do you use?

**Comment by ikifar2012** [comment]
Life360 @pnbruckner

**Comment by pnbruckner** [comment]
@ikifar2012 life360 was accepted as a standard component, which will hopefully be in the 0.95.0 release. Also I do not plan on making any more changes to the custom component, and I will stop supporting the custom component once the standard component is available. Therefore there is no need to support HACS (or even custom_updater) for life360.

**Comment by pnbruckner** [comment]
Support added for Illuminance Sensor: https://github.com/pnbruckner/ha-illuminance. I'll work on Composite Tracker and Sun next.

**Comment by ikifar2012** [comment]
I found the PR for Life360:
https://github.com/home-assistant/home-assistant/pull/24227#issue-284176150

**Comment by cwendigo** [comment]
It will be possible to include light_store into HACS?
Thank you

**Comment by pnbruckner** [comment]
@cwendigo I don't think so. I think it was only designed to support custom components/integrations and custom cards, not python_script's. You'd have to ask the author of HACS.

**Comment by drfschmidt** [comment]
I am also waiting for SUN in HACS.

**Comment by cwendigo** [comment]
@pnbruckner Could you please check this?.
https://custom-components.github.io/hacs/developer/python_script/

**Comment by pnbruckner** [comment]
@cwendigo ok, thanks. I don't know if that's new or now, but last I looked I didn't see any evidence of python_script support. I'll add it to my "to do" list.

**Comment by pnbruckner** [comment]
Composite Device Tracker moved to HACS-compliant repo: https://github.com/pnbruckner/ha-composite-tracker

**Comment by upwindanderl** [comment]
> @cwendigo ok, thanks. I don't know if that's new or now, but last I looked I didn't see any evidence of python_script support. I'll add it to my "to do" list.

how does it look with your todo :) 
i installed hacs just a minute before because of using light_store (your install ndocumentation refers to a hacs installing) now i'm a bit confused
Should i remove my hacs and start with custom_components or should i wait :) 
#nostress but some info when would be cool

**Comment by rdehuyss** [comment]
Would you also consider moving your enhanced sun component to a HACS compatible repo. I'm especially interested in more frequent updates for Azimuth. Now, it can take over 15min

**Comment by jazzyisj** [comment]
Phil - first thank you for sharing your awesome components.  I use light store and composite tracker extensively.  I was poking around on your git and I'm going to give illuminance a whirl also.

Now to my point - I know this is low priority with all the other contributions you are making to HA but it would be great to get light_store on HACS.  It is one of the last things I use that isn't on there.  I think there is a way to arrange your git so that all your components show up, similar to addons?  Maybe not but regardless it is nice to have everything pulled together in HACS - makes updates a breeze.

Either way, thank you!

**Comment by pnbruckner** [comment]
@rdehuyss sorry I didn't see your request until now.

No, I don't plan on making the enhanced sun component HACS compatible. Rather, I've replaced it with a completely new implementation, which should be HACS compatible, and can be found here: https://github.com/pnbruckner/ha-sun2

Now, having said that, the new integration does not support azimuth yet. I am in the process of adding elevation support to it, and once I'm satisfied with that I plan to add azimuth support.

**Comment by pnbruckner** [comment]
@jazzyisj thanks. When HACS first came out I don't think it supported `python_script`'s, but I think it does now. Or, at least, I've heard it does. Honestly, that (and the `custom_component` integration before it) is kind of hard to keep up with. I'll try to see what I can do.

**Comment by pnbruckner** [comment]
With the advent of the new ability to dynamically create scenes on the fly and use them to save & restore entities my light_store.py python_script is no longer needed as much. Therefore I won't bother trying to support HACS.
