### ISSUE TITLE
Life360 Home Assistant 0.95.4 init error

### ISSUE THREAD

**Issue by beniaminrychter** [pnbruckner/homeassistant-config#152]
Hi! After updating HA to 0.95.4 I'm receiving this kind of errors in hass.io console after rebooting: 

`Ignoring: TypeError: 'module' object is not callable`

`Error setting up platform legacy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 76, in async_setup_legacy
    tracker.see, discovery_info)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/life360/device_tracker.py", line 311, in setup_scanner
    Life360Scanner(hass, config, see, interval, home_place_name, api)
UnboundLocalError: local variable 'api' referenced before assignment`

Version of life360: 2.10.1

Before update, everything worked well.

**Comment by CBPetrovic** [comment]
Have you removed the Life360 references / folder from the custom components folder?

I saw the same thing when I updated to 0.95.0, which was resolved by deleting the life360 folder.

**Comment by pnbruckner** [comment]
@beniaminrychter which life360 integration are you trying to use: the original custom one, or the new standard one?

**Comment by beniaminrychter** [comment]
@pnbruckner Oh, I'm so sorry. I didn't noticed that life360 is now integrated in HA. I was using this original custom one. Now is working like a charm 😊 Thank you.
