### ISSUE TITLE
An example in the readme for nodered

### ISSUE THREAD

**Issue by cooljimy84** [pnbruckner/homeassistant-config#153]
I'm trying to call this using Nodered Home assistant, but i get no errors and no restored bits, I've posted on HASS forum as well.

`[{"id":"356d075.6d9c7f8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"868cfaa8.aeefd8","type":"api-call-service","z":"356d075.6d9c7f8","name":"Store Kitchen LEDs","server":"e6482986.08f318","service_domain":"python_script","service":"light_store","data":"{   \"store_name\": \"flash_store\",  \"entity_id\": \"light.kitchen_led_1\" }","mergecontext":"","x":610,"y":220,"wires":[[]]},{"id":"977beba4.1bf438","type":"api-call-service","z":"356d075.6d9c7f8","name":"Restore Lights","server":"e6482986.08f318","service_domain":"python_script","service":"reload","data":"{   \"store_name\": \"flash_store\",  \"operation\": \"restore\" }","mergecontext":"","x":600,"y":280,"wires":[[]]}`

**Comment by pnbruckner** [comment]
@cooljimy84, sorry, I know nothing about node red.
