### ISSUE TITLE
Handle 'tracking disabled' when member is in multiple circles

### ISSUE THREAD

**Issue by eekdood** [pnbruckner/homeassistant-config#22]
Firstly, this is fantastic. Cheers!

Here's our setup: Two circles, one with just the wife and I, and the other with the two of us and the kids. The wife and I have location sharing disabled within the second circle, so we can monitor the kids, but they can't monitor us. HA is correctly tracking the kids, but since we have location sharing disabled in one circle, it's not grabbing our location from the other. Thoughts?

**Comment by pnbruckner** [comment]
Interesting, and thanks for taking the time to open this issue.

I only use one circle, and nobody in our circle has location sharing turned off. So I haven't seen how the server reports that. I did do some testing with a second circle to try and figure out how to manage that. So currently once it sees a member, that member is marked as "updated", so if that member shows up in another circle, it doesn't take the time to update that member again. But clearly I need to add some logic to deal with the member's location sharing being disabled in one or more circles. I'll look into that and see what I can do about it. I'm guessing it should be a relatively easy fix.
