### ISSUE TITLE
Life360: driving attribute doesn't seem to work

### ISSUE THREAD

**Issue by pnbruckner** [pnbruckner/homeassistant-config#23]
Currently the driving attribute is derived from the member's ['location']['isDriving'] field, but this always seems to be '0', even when the member is moving in a car.

A suggestion has been made (see [this HA community post](https://community.home-assistant.io/t/life360-device-tracker-platform/52406/181)) to determine the driving status based on the value of the member's ['location']['speed'] field.

**Comment by pnbruckner** [comment]
So far the numbers I've seen in the speed field (that are not zero or -1) don't seem to have any direct correlation to MPH, or KPH, or even FPS or MPS. Not sure how to derive a driving status from this value.

**Comment by shreram** [comment]
@pnbruckner I believe @skalavala was using 'vel' to identify if the person is driving or not. He has some automations to notify based on person's speed ('vel') value.

Here are the snippets from @skalavala repository.

**MQTT sensor**

https://github.com/skalavala/smarthome/blob/75963efebe47cec32b735c2d5ddea3c8afe9ec07/packages/batteries.yaml#L214

**passing vel to MQTT**

https://github.com/skalavala/smarthome/blob/c7a4f5e8c0deae6990b88c7cd0af3104f4650334/custom_components/sensor/life360.py#L207

**Automation**  (if the speed is above: 8)

https://github.com/skalavala/smarthome/blob/75963efebe47cec32b735c2d5ddea3c8afe9ec07/packages/batteries.yaml#L423

**Comment by hvbhome** [comment]
While I havent been able to use this yet, and indeed don't see Driving other than false, this thread gives food for another question too:

please consider creating and adding the mqtt feature for the component.

On the [forum Ive explained my experiences ](https://community.home-assistant.io/t/life360-device-tracker-platform/52406/190?u=mariusthvdb) with the 2 composite trackers I use now, being this CC and a mqtt setup made out of indivual components like in this CC, albeit manually.

The main difference would be the use of mqtt. This enable me to use the attribute and state values of the CC on other systems as well! Very very convenient.

Would be way cool if you could add that to the CC features.
consider it a feature request ;-)

**Comment by skalavala** [comment]
I've just responded to the thread on the community forum https://community.home-assistant.io/t/life360-device-tracker-platform/52406/192

**Comment by pnbruckner** [comment]
> While I havent been able to use this yet, and indeed don't see Driving other than false, this thread gives food for another question too:
> 
> please consider creating and adding the mqtt feature for the component.
> 
> On the [forum Ive explained my experiences ](https://community.home-assistant.io/t/life360-device-tracker-platform/52406/190?u=mariusthvdb) with the 2 composite trackers I use now, being this CC and a mqtt setup made out of indivual components like in this CC, albeit manually.
> 
> The main difference would be the use of mqtt. This enables me to use the attribute and state values of the CC on other systems as well! Very very convenient.
> 
> Would be way cool if you could add that to the CC features.
> consider it a feature request ;-)

Hi @hvbhome! Thanks. I've opened issue #26 for this request.

**Comment by pnbruckner** [comment]
> So far the numbers I've seen in the speed field (that are not zero or -1) don't seem to have any direct correlation to MPH, or KPH, or even FPS or MPS. Not sure how to derive a driving status from this value.

Based on @skalavala's feedback, and some additional observation while driving on the highway, the speed values seem to be about 2.2 times smaller than the driving speed in mi/h (aka mph.)

I think I'll add a new config item called 'min_driving_speed' that, if specified in the config, will be used to compare against the speed value obtained from the server. The driving attribute will then be effectively isDriving or speed > min_driving_speed. The only question is whether or not to make the config item a "raw" value to be compared directly against the speed from the server, or if it should try to be in mph (with a guessed factor of 2.2) and/or even in km/h (with an appropriate factor.)

**Comment by hvbhome** [comment]
cool, nice development!
If I might add to this:

> The only question is whether or not to make the config item a "raw" value to be compared directly against the speed from the server, or if it should try to be in mph (with a guessed factor of 2.2) and/or even in km/h (with an appropriate factor.)

I'd say to keep it as straight from the server, "raw" as possible. Until we understand what number Life360 uses (...) we can always template some appropriate factor against it in our HA logic. Approximation is never very helpful, especially if its only on guessing the numbers?
my 2 cents only.cheers,
Marius

btw, Ive now set driving messages on all circle members, and still see driving: false. It does see me moving:-)

**Comment by pnbruckner** [comment]
Good points, thanks. My current thinking is to allow one of three options: min_driving_speed (i.e, raw), min_driving_speed_mph or min_driving_speed_kph, the latter two using best guess factors, which right now seems to be about 2.25 for mph. The factor can always be refined over time. Although I suspect the numbers from the server are pretty rough anyway.

**Comment by shreram** [comment]
> Good points, thanks. My current thinking is to allow one of three options: min_driving_speed (i.e, raw), min_driving_speed_mph or min_driving_speed_kph,  

That's a good idea. But if that's too much work on you then just keep it as it is 'vel' ( mentioned by @hvbhome) and let the user control the speed logic via automation (like the way @skalavala did).

**Comment by pnbruckner** [comment]
Decided to have two attributes: raw_speed and speed. The latter will be in MPH or KPH (depending on HA's unit system configuration) and will be calculated using the best guess factor. Also will have just the one driving_speed option (which also will depend on the unit system config.) So most people can use units they're used to, but for those that want the raw speed that Life360 reports it will be there, too.
