### ISSUE TITLE
Composite tracker: Add support for network-based trackers

### ISSUE THREAD

**Issue by pnbruckner** [pnbruckner/homeassistant-config#25]
The component level device tracker code has provisions for merging updates from one or more network-based trackers and a GPS-based one by assigning the same MAC address to the GPS-based tracker in known_devices.yaml. However, network-based trackers suffer from the fact that many, if not most, battery operated devices (like cell phones) tend to stop responding to pings, etc. for sometimes long periods of time (presumably to save battery charge), and hence it's not uncommon for these network-based trackers to change state to 'not_home', even though the device is still home.

So far the composite device tracker platform only supports GPS-based trackers. But if it allowed network-based trackers as well, their 'not_home' to 'home' transitions could be used to more quickly change the composite tracker to 'home' (before the GPS-based trackers get around to updating to 'home'.) And since the network-based 'home' to 'not_home' transitions tend to be fairly unreliable, and are a guess at best, they would just be ignored.

**Comment by pnbruckner** [comment]
So far it appears that network-based trackers set source_type to SOURCE_TYPE_ROUTER (i.e., 'router'.) This seems like it could be used to automatically tell when an input entity is network-based, and hence should only take into account a new_state of 'home' (and to ignore other states.)

**Comment by pnbruckner** [comment]
Another question: for network-based trackers, it seems when they are updated, they get the GPS coordinates of the home zone (if one is defined.) Should this be used, and if so, when? E.g., if the last GPS-based tracker update was outside the home zone, and a network-based tracker changes state to 'home', then the GPS data should probably be used. But once the composite tracker has GPS coordinates inside the home zone (either from this, or from the GPS-based tracker updating), then any new transition to 'home' of a network-based tracker should probably ignore the GPS data (since it's probably not as accurate as what the GPS-based tracker provided.)

**Comment by hvbhome** [comment]
this could possibly be the answer to these horribly unreliable network trackers...
Ive done about all preventing incorrect location change triggers firing the action in conditions, (gps coordinates, time, rule out attributes changes etc etc), but they keep triggering when switching from not_home to home, when in fact a home...

see for example:

```
    condition:
      - condition: template
        value_template: >
          {{ trigger.to_state.state is not none and
             trigger.from_state.state is not none and
             trigger.to_state.state != trigger.from_state.state }}
#      - condition: template
#        value_template: >
#          {{trigger.to_state.attributes.longitude != 
#              trigger.from_state.attributes.longitude and 
#            trigger.to_state.attributes.latitude != 
#              trigger.from_state.attributes.latitude }}
      - condition: template
        value_template: >
          {% set zones = states.zone | map(attribute='entity_id')|list %}
          {{trigger.to_state.state in ['home','not_home'] or
            trigger.from_state.state in ['home','not_home'] or
            trigger.to_state.state in zones or 
            trigger.from_state.state in zones}}
      - condition: template
        value_template: >
          {{ (now() - trigger.from_state.last_changed | default(0)).total_seconds() > 360 }}
 

```
also, use the consider_home setting of the device_tracker, which is set globally per component, but which can also be set per device_tracker.

So yes, you should ignore the not_home if gps checks still at home. But then, how to prevent switching to 'home' from triggering a move.... you should also ignore that when gps checks still at home.

Hope this helps....
happy to test if you need

**Comment by hvbhome** [comment]
second post, sorry...

thought I'd share the mqtt tracker developed with the suggestions and big help by @notoriousbdg that combines just these trackers, network and gps based, and uses the gps based tracker gps coordinates in the network trackers:

```
  - alias: M Presence Update from GPS
    trigger:
      platform: state
      entity_id:
#        - device_tracker.telefoon
        - device_tracker.owntracks
        - device_tracker.life360_m
        - device_tracker.telefoonmhb
    action:
      service: mqtt.publish
      data_template:
        topic: "location/m"
        retain: true
        payload: >-
          {
            "latitude": "{{ trigger.to_state.attributes.latitude }}",
            "longitude": "{{ trigger.to_state.attributes.longitude }}",
            "battery_level": {{ trigger.to_state.attributes.battery | int }} ,
            "gps_accuracy": {{ trigger.to_state.attributes.gps_accuracy | int }}
          }

  - alias: M Presence Update from Router or Bluetooth
    trigger:
      platform: state
      entity_id:
        - device_tracker.ping_telefoon
        - device_tracker.telefoon_m_bt
        - device_tracker.m
      to: home
    action:
      service: mqtt.publish
      data_template:
        topic: "location/m"
        retain: true
        payload: >-
          {
            "latitude": "{{ states.zone.home.attributes.latitude }}",
            "longitude": "{{ states.zone.home.attributes.longitude }}",
            "battery_level": {{state_attr('device_tracker.life360_m','battery')|int}},
            "gps_accuracy": 0
          }
```

it's spot on.
hope this helps 2

**Comment by pnbruckner** [comment]
Thanks for the input. FWIW, in the current implementation, if an "input" entity does not have a battery attribute, then the current value of the battery attribute will not change. E.g., I've used it with Life360 and Google Maps, and Google Maps doesn't (or at least didn't) have a battery attribute. In this case the battery attribute of the composite device_tracker only followed the battery level reported by Life360.

**Comment by jwelter1971** [comment]
I notice that using the unifi device tracker I do get a lat/lng when I am in my "home" network; the assumption it makes is this network is the same location you have defined for "home".  When away those fields go away.

Ideally all this could be handled much better in your component as I find that the network trackers are very good at detecting when you arrive at a location but not so great as realizing you've left - they tend to be slow on that transition also to prevent false aways if a device sleeps (typically a 300 second transition to being away).

I've played around combining this all in elaborate automations and such but they are horrific to maintain.

**Comment by pnbruckner** [comment]
I've changed a bit how I'm handling network-based trackers (i.e., those whose source_type attribute is 'router'.) It should now handle a mix of 'gps' and 'router', or all of one type or the other.

When there's a mix (and at least one 'gps' tracker has changed state), then as before, only 'home' states of 'router' trackers will be used. And in this case any previous GPS data takes precedence over any GPS data that comes from the 'router' tracker.

When there's only 'router' trackers (or before any 'gps' tracker changes state), then the last known state of each 'router' tracker will be stored, and the composite tracker will only be "seen" when a 'router' tracker's state changes and it _is_ 'home' (in which case the composite tracker will be 'home'), or when one changes and it is _not_ 'home' _and all_ 'router' trackers' states are not 'home' (in which case the composite tracker will be 'not_home'.)
