### ISSUE TITLE
Composite tracker: AttributeError with tzinfo

### ISSUE THREAD

**Issue by jwelter1971** [pnbruckner/homeassistant-config#30]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/device_tracker/composite.py", line 106, in _update_info
    new_state.last_updated))
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/dt.py", line 66, in as_utc
    if dattim.tzinfo == UTC:
AttributeError: 'int' object has no attribute 'tzinfo'
```

**Comment by jwelter1971** [comment]
Error is generated as the Unifi WAP component returns a "last_seen" time in the format of 1537653693.  Disabling the Unifi component to not return this field causes this error to go away; but without getting last_time updates of the component.

**Comment by pnbruckner** [comment]
According to [this unifi code](https://github.com/home-assistant/home-assistant/blob/bc8d323bdd6a66fba254d20b0339603fe6bd63ec/homeassistant/components/device_tracker/unifi.py#L121-L125), it looks like last_seen is indeed a timestamp, either as a number or a string. I'll look at adding code that tries the last_seen attribute as a timestamp if it fails to work as a datetime.
