### ISSUE TITLE
'moving' while at home

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/homeassistant-config#40]
HI,

Just noticed that the 'moving' attribute was 'true', while being 'Home' for rather a long while. Not sure if this is a bug, or a direct consequence of settings in device_tracker 'consider home' or Life360 setup, but might be worth having a second look.

I noticed it because I based the imagery of certain tiles on that attribute.... and it obviously wasn't correct ;-)
It cant have been the fact the device wasn't last seen shortly enough, since it did change the state to Home correctly.

**Comment by pnbruckner** [comment]
That attribute comes directly from the Life360 server. It is not filtered in any way. And depending on how big your home zone is, it is very possible that you could be moving and still be considered 'home'. In fact, I just noticed that was true for me yesterday as drove into my home zone (while I was testing the new feature to base driving status on reported speed.)

I think you'll just need to take into account both the moving attribute and the "'home' or not" state of the device_tracker. I don't think that this attribute should be filtered, especially as I said, it is indeed possible to be moving within a zone.
