### ISSUE TITLE
Life360: Event type too long for mysql recorder

### ISSUE THREAD

**Issue by jerobins** [pnbruckner/homeassistant-config#57]
From the logs:

`Error executing query: (_mysql_exceptions.DataError) (1406, "Data too long for column 'event_type' at row 1") [SQL: 'INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)'] [parameters: ('device_tracker.life360_update_overdue', '{"entity_id": "device_tracker.life360_ABBADABBA"}', 'LOCAL', datetime.datetime(2018, 10, 24, 15, 35, 27, 241056, tzinfo=<UTC>), datetime.datetime(2018, 10, 24, 15, 35, 27, 243863), '69903c9481a3485299ab0e14549e059b', None)] (Background on this error at: http://sqlalche.me/e/9h9h)
11:35 AM components/recorder/util.py (ERROR)`

**Comment by pnbruckner** [comment]
@jerobins, see beta fix in referenced PR. If you can give it a try then let me know if that resolves the problem.

**Comment by jerobins** [comment]
@pnbruckner that works, thanks! Is it worth pointing out the length limit to the HA dev folks? My first reaction when I saw the error was, "wow, why is that so short." Perhaps it was an oversight.
