### ISSUE TITLE
Multiple composite tracker support? 

### ISSUE THREAD

**Issue by mrneilix** [pnbruckner/homeassistant-config#64]
Hey, I really love what you did here! I was wondering if it was possible to add multiple composite trackers for different people? I've been using binary sensors for when my family visits, along with using monitor and tile to check if my dog if home too. I like the composite tracker a lot more though

**Comment by pnbruckner** [comment]
Yes, you can configure multiple composite trackers, each for a different person. Just add a new entry for each person, giving a unique name, and then list the corresponding entity or entities to watch for that person.

**Comment by pnbruckner** [comment]
@mrneilix, did that answer your questions, or do you still need help, or want to report a bug or make a feature request?

**Comment by mrneilix** [comment]
Hey! Thanks! Yeah, it worked after I moved to hassos from ResinOS on hassio. I think it was just something on my system that was buggy. Thanks so much and keep up the awesome work!
