### ISSUE TITLE
life360 added life360.py file, and configuration but nothing happens.

### ISSUE THREAD

**Issue by aaamoeder** [pnbruckner/homeassistant-config#71]
I did everything step by step but after a reboot, life360 is not showing. Instead, my gpslogger entities are gone when I enable life360.

When I comment out life360, gpslogger works fine again.

please advise

(running latest version of hassio)

**Comment by pnbruckner** [comment]
Is it possible that gpslogger and life360 are trying to create entities with the same entity_id's? Have you checked known_devices.yaml? Are you using the optional prefix config item for life360 to make sure there aren't any entity_id conflicts between life360 and gpslogger? Are you seeing any errors in the log? Those are the only things that come to mind that I could think of where the two platforms could possibly affect each other.

**Comment by pnbruckner** [comment]
Can you check that you copied the file correctly? One common mistake is that people download the HTML page instead of clicking on the Raw button to get the actual file content. Did you install "manually", or did you use the Custom Updater to install this?

**Comment by pnbruckner** [comment]
Actually, I'm almost positive that's the problem. You cannot right-click on the link on the doc page and select save as, you have to left-click on it, then on the page that shows the file you can right-click on the Raw button and select save as. I know this is confusing if you've never really used github before. I'll try to improve the instructions to hopefully prevent this problem in the future.

**Comment by aaamoeder** [comment]
sorry for the late reply.. busy weekend..

I had indeed copypasted the wrong file, but now with the correct file it still doesn't work.
This is the error

> 2018-12-02 13:45:18 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform life360
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 184, in async_setup_platform
    disc_info)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/device_tracker/life360.py", line 126, in setup_scanner
    from life360 import life360
ModuleNotFoundError: No module named 'life360'

The issue of my dissapearing gpslogger devices is gone though. they show as normal when both gpslogger and life360 are enabled in device_tracker.yaml

**Comment by pnbruckner** [comment]
Does it still happen after another restart? HA is supposed to automatically install that module, but I've seen some people have this issue. Do you see any errors in your log saying it couldn't install all requirements?

**Comment by aaamoeder** [comment]
You're right.

After multiple restarts today it seems to be working ! Thanks for the help ;)
