### ISSUE TITLE
Life360 On Docker - get_circles: ReadTimeout

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [pnbruckner/homeassistant-config#72]
I have just tried getting the life360 custom component to work in Docker (not sure if it is Docker that is causing the issue??)

The component seems to load correctly however nothing happens.

When looking at the traceback, I can see this error:

> 2018-11-28 14:26:41 ERROR (SyncWorker_7) [custom_components.device_tracker.life360] get_circles: ReadTimeout: HTTPSConnectionPool(host='api.life360.com', port=443): Read timed out. (read timeout=11.0)

config file is a textbook extract from the example hosted in this wiki (I am using email not phone number for username).

Latest version of HomeAssistant (0.82.1)

**Comment by pnbruckner** [comment]
It's not uncommon to sometimes see communications errors. But generally not so much as to keep it from working (i.e., successfully retrieving information from the Life360 server.) If the comm failure happens during startup, however, it's possible it will give up. I actually have an issue open for that, although I don't know that in practice this has happened. If it won't work for you after one or more restarts, then possibly HA is not able to communicate with the outside world??? Are other components working for you that need to access the Internet?

**Comment by danieledwardgeorgehitchcock** [comment]
Seems to have fixed itself (didn't change anything)

Thanks for your help!
