### ISSUE TITLE
Members not removed

### ISSUE THREAD

**Issue by T2evh** [pnbruckner/homeassistant-config#88]
I've removed two members from the Life360 app two days ago, but they still appear on HA. I've restarted but they're still there. Any suggestions wecome. Thanks

**Comment by pnbruckner** [comment]
@T2evh, you need to either manually remove them from known_devices.yaml, or change their track entry in that file to False. That's just the way the component-level device_tracker code works. When a device is first seen, it gets entered into known_devices.yaml. And at every restart that file is read and entities are created for all the listed devices, even if they are never seen again. Basically, AFAIK, there are no automatic provisions for removing devices.

**Comment by T2evh** [comment]
Thank you for your support
