### ISSUE TITLE
Error installing requirements for life360.py

### ISSUE THREAD

**Issue by mikeage** [pnbruckner/homeassistant-config#90]
Hi, 
After I upgraded from 2.3 to 2.5, I see the following error in my log:
```
Jan 31 06:55:33 raspberrypi hass[31028]: 2019-01-31 06:55:33 INFO (Thread-7) [pyupdate.ha_custom.custom_components] Upgrading life360==2.*timezonefinderL==2.*
Jan 31 06:55:38 raspberrypi hass[31028]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Jan 31 06:55:38 raspberrypi hass[31028]: Collecting life360==2.*timezonefinderL==2.*
Jan 31 06:55:40 raspberrypi hass[31028]:   Could not find a version that satisfies the requirement life360==2.*timezonefinderL==2.* (from versions: 2.0.0.dev2, 2.0.0)
Jan 31 06:55:40 raspberrypi hass[31028]: No matching distribution found for life360==2.*timezonefinderL==2.*
Jan 31 06:55:41 raspberrypi hass[31028]: 2019-01-31 06:55:41 INFO (Thread-7) [pyupdate.ha_custom.custom_components] upgrade_single finished: "device_tracker.life360"
```
I have absolutely no idea why it's stripping the , and trying to install one package instead of two, and other files seem to install their requirements just fine. Any ideas what might be wrong?

**Comment by pnbruckner** [comment]
This would be a bug in the custom updater. You might want to log the issue [there](https://github.com/custom-components/custom_updater/issues).

**Comment by ludeeus** [comment]
Logging it there would have resulted in me seeing it faster :)
Should now be corrected in the newest version of `pyupdate` and `custom_updater`
The issue was that the requirements were split with `,` and not the default `, `

**Comment by pnbruckner** [comment]
@ludeeus, FWIW, there is no "default", or any defined format, other than REQUIREMENTS must be a module level variable that is a list of strings.

**Comment by mikeage** [comment]
Thanks! I'm new to the custom updater and didn't even think to check what mechanism it used for installing packages.

**Comment by ludeeus** [comment]
With "default" I meant that most python style guides and linters expect there to be a space after the comma :)

**Comment by pnbruckner** [comment]
@ludeeus, yep, and I usually put a space after a comma, too. Not sure why I didn't here. I'll probably change that whenever I make the next update.
