### ISSUE TITLE
Hassio Error: 

### ISSUE THREAD

**Issue by P2mb2** [pnbruckner/homeassistant-config#97]
So... i created the directory tree with life360.py on device_tracker folder. I added to my configuration.yaml

device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    add_zones: all
    max_gps_accuracy: 200
    prefix: life360
    show_as_state: driving, moving, places

I get this error when restarting ha:

> 2019-02-17 19:28:03 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package timezonefinderL==2.0.1: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/timezonefinderl/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/timezonefinderl/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/timezonefinderl/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/timezonefinderl/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))': /simple/timezonefinderl/
  Could not find a version that satisfies the requirement timezonefinderL==2.0.1 (from versions: )
No matching distribution found for timezonefinderL==2.0.1
2019-02-17 19:28:03 ERROR (MainThread) [homeassistant.requirements] Not initializing device_tracker.life360 because could not install requirement timezonefinderL==2.0.1
2019-02-17 19:28:03 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform device_tracker.life360: Could not install all requirements.

Any help ?

**Comment by pnbruckner** [comment]
All I can suggest is restarting and trying again. That is a standard package on [PyPI](https://pypi.org/project/timezonefinderL/). If HA can't download and install it, then maybe there's an intermittent network problem.

**Comment by pnbruckner** [comment]
@P2mb2, have you made any progress? Is it working, or are you still having problems?

**Comment by P2mb2** [comment]
Hi pnbruckner, 

Thanks for the reply. I tried today again... and just as you mention... it worked. 
Intermittent network problem indeed.

Thanks.
